#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage: ${0##*/}  bitbucket_username(not email)  repository_name" >&2
  exit 1
fi
username="$1"
reponame="$2"
printf "\nPlease insert Bitbucket password: "
read -s password 

#Create repo using curl and Bitbucket REST API v2.0
curl -X POST -v -u $username:$password -H "Content-Type: application/json" \
https://api.bitbucket.org/2.0/repositories/$username/$reponame \
-d '{"scm": "git", "is_private": "true", "fork_policy": "no_public_forks" }'

printf "\nRemote repository https://$username@bitbucket.org/$username/$reponame.git created\n\n"

git init
git add .
git commit -a -m "Initial automatic commit $(date)"
git remote add origin https://$username@bitbucket.org/$username/$reponame.git

#If you want to store the password uncomment the next line
#git config credential.helper store

git push -u origin master

printf "\nFinished\n\n"
