#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage: ${0##*/}  bitbucket_username(not email)  repository_name" >&2
  exit 1
fi
username="$1"
reponame="$2"
printf "\nPlease insert Bitbucket password: "
read -s password 

#Create repo using curl and Bitbucket REST API v2.0
curl -X POST -v -u $username:$password -H "Content-Type: application/json" \
https://api.bitbucket.org/2.0/repositories/$username/$reponame \
-d '{"scm": "hg", "is_private": "true", "fork_policy": "no_public_forks" }'

printf "\nRemote repository https://$username@bitbucket.org/$username/$reponame created\n\n"

hg init
hg add
hg commit -m "Initial automatic commit $(date)"

echo \[paths\] >> .hg/hgrc
echo default = https://$username@bitbucket.org/$username/$reponame >> .hg/hgrc
echo \[ui\] >> .hg/hgrc
echo username = $username >> .hg/hgrc
echo \[auth\] >> .hg/hgrc
echo bb.prefix = https://bitbucket.org >> .hg/hgrc
echo bb.username = $username >> .hg/hgrc

#If you want to store the password uncomment the next line
#echo bb.password = $password >> .hg/hgrc

hg push https://$username:$password@bitbucket.org/$username/$reponame

printf "\nFinished\n\n"
